create table if not exists image
(
    id bigint generated by default as identity
    constraint image_pkey
    primary key,
    file_name varchar(255)
    );

create table if not exists image_tag
(
    id bigint generated by default as identity
    constraint image_tag_pkey
    primary key,
    image_tag varchar(255),
    image_id bigint
    constraint fkgb0metxaw60hmykntems06t5n
    references image
    );